### ISSUE TITLE
turf.js topology error

### ISSUE THREAD

**Issue by nerik** [hotosm/osm-analytics#78] opened 2017-10-02 08:18 UTC
Currently when querying some areas (for example 'Zanzibar') using the Overpass API, the mechanism to pick tiles within the shape returned by it fails with a `jsts.error.TopologyError` runtime error: 
```
found non-noded intersection between LINESTRING ( 39.72757 -5.2045, 39.67808 -5.21448 ) and LINESTRING ( 39.65877 -5.20819, 39.7484 -5.23422 ) [ (39.67946610320799, -5.214200482723465) ]
```
This happen's when turf.js' `intersect` method is called: 
https://github.com/hotosm/osm-analytics/blob/master/app/components/Stats/searchFeatures.js#L71

This PR https://github.com/GFDRR/osm-analytics/pull/19/files will avoid completely crashing the stats module by using all tiles as a fallback. This is not an optimal solution and the actual issue needs to be addressed.

**Comment by tyrasd** [comment] 2018-02-19 16:08
duplicate of #51 and fixed by merging cc6029f906eec3e1353ff42fe395dfc0ec67224e

> by using all tiles as a fallback

This actually isn't such a bad workaround, since the only downside of iterating over all tiles is only a performance issue and typically regions aren't _that_ concave to make a huge difference, I would guess.

**Closed by tyrasd** 2018-02-19 16:08 UTC
