### ISSUE TITLE
Can't load the Gap Detection layer

### ISSUE THREAD

**Issue by ppasq** [hotosm/osm-analytics#84] opened 2018-07-16 14:03 UTC
@tyrasd I can't load the Gap Detection layer. I'm getting:
`Failed to load resource: the server responded with a status of 404 (Not Found)`
on 129.206.7.145:7779/buildings/5/16/17.pbf:1
and several 
`Failed to load resource: net::ERR_CONNECTION_TIMED_OUT`
on 129.206.7.145:7778/x/x/x.pbf:1
Using both Chrome and Safari on MacOS.

**Comment by tyrasd** [comment] 2018-07-19 08:15
It's normal to have some 404's in the network traffic, since some areas of the world just have no buildings. Also the reference data for the gap analysis is (for now) only available for the central African continent.

> ERR_CONNECTION_TIMED_OUT

This looks like the actual error here. Not sure what might have caused this. Does it still not work for you? Can you perhaps test it on a different computer?

**Comment by tyrasd** [comment] 2018-07-27 07:37
I'm closing this ticket here, since the error was not reproducible (and beacuse, in the meantime, we've switched the osma vector tile server to standard ports, so it should not be an issue anymore).

**Closed by tyrasd** 2018-07-27 07:37 UTC

**Comment by ppasq** [comment] 2018-07-27 07:40
@tyrasd Yes, I confirm. Now the layer works fine for me as well.
